version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api-server
    ports:
      - '4000:4000'
    env_file:
      - .env
    volumes:
      - /app/node_modules
      - ./data:/app/data
      - ./src:/app/src
    restart: unless-stopped
